python/python-docs-fr

- library/datetime.po
Bonsoir,
Je suis enfin venu à bout de `library/datetime.po`, donc voici les dernières traductions pour compléter la documentation du module.
> Complete library/datetime.po

- library/json.po
- library/re.po
Bonsoir,
J'ai fini de compléter les traductions du fichier `library/json.po`.
Je profite de la *PR* pour apporter une correction sur le terme « formaté » dans `library/re.po`.
> Complete library/json.po

- README.rst
The link was broken because the scheme was missing.
> Fix the IRC link in the README

- library/pipes.po
Traduction complète de la doc de la libraire pipes.
> Traduction de pipes.po

- library/html.entities.po
Sur la lancée des modules html.
> Traduction de 'html.entities'

- Makefile
- add a rule that upgrades virtual env
- add a JOBS parameter to Sphinx to specify the number of jobs (commands)
to run simultaneously
> Makefile enhancement:

- reference/simple_stmts.po
Completed.
Requires proofreading.
> 'Reference - Simple Statements' Translation

- TRANSLATORS
- library/modulefinder.po
> Translate `modulefinder.po`

- library/modulefinder.po
* reStructuredText is playful, tokens have a different meaning if they are placed just after a space or a non-space character
* actually use non-breakable spaces
> Fix translations for `library/modulefinder.po`

- library/ast.po
- library/copy.po
> Translate library/copy.po

- library/readline.po
I am not sure about the * : ::* tokens, the render in the final python doc isn't good for me.
and the link 
https://cnswww.cns.cwru.edu/php/chet/readline/rluserman.html#SEC9
seems broken at the moment.
I hope there is not too much left errors.
> translate library/readline

- library/zipfile.po
Closes https://github.com/python/python-docs-fr/issues/371
> Translate library/zipfile.po

- scripts/todo.py
This is to prevent the cases like https://github.com/python/python-docs-fr/issues/439
> Added lower() to issue names - todo.py

- library/functions.po
#569 correction d'une typo, répare un lien automatique.
> Correction de typo dans functions (description de repr)

- tutorial/controlflow.po
> Fixed fuzzys in tutorial/controlflow

- tutorial/interpreter.po
> Fixed fuzzys in tutorial/interpreter.po

- library/subprocess.po
> Fixed fuzzys in library/subprocess.po

- faq/general.po
je mets pas tout le texte d'origine dans la balise (*sphinx documentation tool*) et c'est voulu.
> corrige une balise cassée

- README.rst
la ligne de 'setter' que j'ai ajouté dans le README coupe celle de 'return', et casse le README.
> répare le README

- howto/unicode.po
- reference/import.po
Christophe a cassé le master en oubliant de wrapper `reference/import.po` lors de #797, qui a été mergée, et Julien a introduit une string contenant `pouette « ss » pouette` lors de fa3683a1de8106185232e2e23eec5139da9575d2, du coup la CI voit rouge tout le temps :)
> wrap reference/import.po (pour réparer la CI)

- .travis.yml
because the master branch is 3.7 so it's only logical to have py 3.7 as well
> Update .travis.yml to use python 3.7

- README.rst
- TRANSLATORS
Quelques modifications du README :
- utilisation des guillemets français
- ajout du pdf de typographie de J. André dans la section bibliographie (et suppression lien mort)
- quelques modifications au glossaire (et en particulier on ne conseille plus d'utiliser «i.e» ou «e.g»)
- 2 ou 3 corrections mineures en passant
Vous pouvez voir le rendu sur mon fork : https://github.com/awecx/python-docs-fr/tree/doc
Je me suis ajouté au fichier TRANSLATORS
> Modifications README et TRANSLATORS

- README.rst
Lors de la traduction j'ai changé accidentellement le nombre de tirets simples nécéssaires à faire un em-dash (j'en ai mis 5 au lieu 3) et incorrectement changé le caractère du en-dash par un mauvais (tiret simple).
> README: mauvais nombre de tirets pour em-dash + mauvais caractère en-dash

- howto/functional.po
Ça se voyait lorsqu'on lisait la doc dans une petite fenêtre : les deux-points allaient tout seuls à la ligne suivante
> howto/functional: espaces insécables avant les deux-points

- library/pathlib.po
> Traduction de pathlib

- README.rst
> ajout de "backtrace/stacktrace" -> "pile d'appels, trace de pile" dans le glossaire

- Makefile
This shows:
```
Build success, files in ../cpython/Doc/build/html, run 'make serve' or 'python3 -m http.server -d ../cpython/Doc/build/html' to see them.
```
after a `make`. 
Then `make serve` gives:
```
$ make serve
make -C ../cpython//Doc/ serve
make[1]: Entering directory '/home/mdk/clones/python/cpython/Doc'
python3 ../Tools/scripts/serve.py build/html
Serving build/html on port 8000, control-C to stop
127.0.0.1 - - [14/Nov/2019 23:48:53] "GET / HTTP/1.1" 200 10365
```
> Tell where html is output, and how to see them.

- library/pathlib.po
clos rien du tout, j'ai pas réservé…
J'ai utilisé https://github.com/vpoulailleau/padpo
> use padpo, translate fuzzy and empty translation

- .travis.yml
So I use `grep -c` instead of `wc -l`, to also count the last line, which does not end to a newline due to bash removing it. grep works as expected to count lines, see:
```
$ printf "" | wc -l
0  # Right!
$ printf "" | grep -c ''
0  # Right!
$ printf "a line" | wc -l
0  # Wrong but it's not wc -l fault, files should end with newlines anyway.
$ printf "a line" | grep -c ''
1  # Right!
```
> Forgot that command substitution removes trailing newlines.

- .travis.yml
On the last PR I've checked, travis `$CHANGED_FILES` contained the expected value. So if I did this right, it may work.
> Travis: Only test changed files

- library/asyncio-llapi-index.po
- library/asyncio-subprocess.po
- library/random.po
- library/socket.po
- library/sysconfig.po
- whatsnew/2.5.po
- whatsnew/3.8.po
I mean:
```
pomerge --from-files *.po */*.po
pomerge --no-overwrite --to-files *.po */*.po
powrap -m
```
> Passing pomerge locally.

- reference/datamodel.po
> Fixing fuzzies.

- Makefile
Ça affiche :
```
Build success, open file:///home/mdk/clones/python/cpython/Doc/build/html/index.html or run 'make serve' to see them.
```
et dans certains émulateurs de terminal, ce lien est cliquable, et donc l'utilisateur peut directement aller lire la doc sans avoir a taper `python3 -m http.server...` ou même `make serve`, juste à cliquer.
> Propose to directly open static files.

- Makefile
A useless "-U" was remaining in a pip install, leading to pip hitting
internet every time for nothing.
> Quieter and faster install of dependencies.

- extending/embedding.po
> modification du fichier embedding.po

- library/multiprocessing.po
> Correction fuzzy library/multiprocessing

- library/__future__.po
As explained in https://bugs.python.org/issue39861, a typo in the French translation of `library/__future__.po` makes the wrong reference to PEP 328 instead of PEP 238.
I'm not sure if I followed the correct contributing guidelines since I'm not fluent in French. Let me know if I need to take further action to fix this minor bug.
> Fix reference to PEP 238 in library/__future__.po translation

- tutorial/errors.po
bien que valide, powrap aime pas l'endroit où j'ai placé les commentaires gettext. Cette PR corrige cela.
> tutorial/errors.po: corrige erreur powrap due commentaire gettext

- CONTRIBUTING.rst
Listes et sous-listes sans majuscules au début de chaque ligne et signe de ponctuation correct à la fin de celle-ci.
Le résultat est ici https://github.com/awecx/python-docs-fr/blob/contributing_misc/CONTRIBUTING.rst#ressources-de-traduction.
Je fais une autre PR avec des explications pour les énumérations au sein de la doc.
> Améliorations de la section « Ressources de traduction » de CONTRIBUTING.rst

- dict
- tutorial/controlflow.po
J'ai rajouté "d'ambigüité" dans le dict sinon ça ne passait pas avec pospell
> Correction coquille tutorial/controlflow.po

- Makefile
- plus incrémental en ne recompilant que le fichiers modifiés (le -u dans) ;
- plus informatif en affichant la liste des fichier sà recompiler (-v + le cut) ;
- moins verbeux avec le .SILENT (et donc les @ sont inutiles).
@JulienPalard revue steuplé
@deronnax ça passe sous OS X ?
> Améliorations Makefile (+ incrémental et - verbeux).

- CONTRIBUTING.rst
- découpage plus granulaire de la section « Instructions » ;
- instructions pour le « make serve » ;
- `make todo` plutôt que `potodo` (remonté par @deronnax sur #1289) ;
- autres modifications mineures.
Les changements sont visibles [ici](https://github.com/awecx/python-docs-fr/blob/contributing_5/CONTRIBUTING.rst).
> Encore des changements sur le README.

- CONTRIBUTING.rst
- Makefile
- README.rst
> Makefile mac fix

- c-api/call.po
- c-api/memory.po
- c-api/structures.po
- c-api/tuple.po
- dict
- library/datetime.po
- library/devmode.po
- library/logging.config.po
- library/logging.handlers.po
- library/msilib.po
- library/multiprocessing.shared_memory.po
- library/resource.po
- library/sunau.po
- library/tarfile.po
- library/tkinter.ttk.po
- library/zoneinfo.po
- whatsnew/2.7.po
- whatsnew/3.2.po
- whatsnew/3.3.po
- whatsnew/3.7.po
- whatsnew/3.9.po
En utilisant https://github.com/python/python-docs-fr/pull/1339
Les paragraphes viennent donc de la 3.8, je n'ai rien écrit moi même, ce n'est pas *vraiment* la peine de relire (s'il y a une erreur, on peut la corriger dans une autre PR).
> Forward porting from 3.8.

- library/os.po
Quelque fuzzies très simples plus une reformulation que je trouve importante :
On a pas mal traduit "byte objects" par "objets octets", ce qui pour moi n'a pas de sens tel quel en français (c'est quoi, une socket qui accepte des octets ? une pipe, une memory view ? Au fait, ça en accepte ou ça en donne ? Les deux, peut être ?). On sait qu'en fait c'est une séquence d'octets, donc hop reformulation.
Ça pourrait peut être faire une guideline.
> library/os: quelques fuzzies simples + une reformulation

- library/json.po
on a pas de traduction pour *whitespace*, que le texte original adore utiliser.
> rapide relecture library/json.po

- library/math.po
Bonjour,
Afin de me préparer à un atelier de traduction de la doc python-docs-fr, je voulais tester le processus. J'ai fait une très courte traduction de la description d'une seule fonction. 
J'ai suivi les instructions au meilleur de mes connaissances.
Dites-moi ce qu'il en est :smiley:
Closes #1379 .
> translated 'math.nextafter(x,y)'

- tutorial/classes.po
- tutorial/controlflow.po
pas de correction coté français car c'était des erreurs upstream, déjà corrigées downstream
controlflow.po : https://github.com/python/cpython/commit/72d5ddb930030c16851a98384b053bb99d6cd6f2
classes.po: python/cpython@8f88190af529543c84d5dc78f19abbfd73335cf4
> corrige 2 fuzzies

- howto/sockets.po
Posix a été corrigé en POSIX upstream (par moi), la correction est déjà présente downstream.
> retire marqueur fuzzy d'une chaine corrigée upstream

- library/stdtypes.po
mais toute la page mériterait une relecture, c'est traduit comme en 2012
> library/stdtypes: accorde le participe passé de "entré"

- .github/workflows/tests.yml
It should not take long, but we've seen it timeouting (probably for
another reason that really taking 6+ hours), so a shorter timeout may
be sane here.
> Set a shorter timeout on this build (6h by default).

- .github/workflows/tests.yml
I expect the issue fixed by this PR to impact all PRs from now.
TL;DR: Bump from Python 3.9.0 to 3.9.1 broke a symlink in the cpython/Doc/venv/, added a check to rebuild the venv if the symlink is broken.
> Workaround Python upgrades and venv caching.

- CONTRIBUTING.rst
Seen while fixing https://github.com/AFPy/padpo/issues/58
> fix alphabetical order in glossary

- glossary.po
see: https://github.com/sphinx-doc/sphinx/issues/9019
> Fix: Compatibility with Sphinx>=3.3.1.

- Makefile
So they use the Sphinx required from our branch, not the Sphinx from another random branch.
Fixes: #1556
> FIX: Checkout before telling the user to install Sphinx.

- .potodoignore
This was causing confusion, mainly for me, as I thought the `glossary.po` displayed was the one on the root of the project, creating this issue:
https://github.com/AFPy/Potodo/issues/115
> Added locales folder to potodoignore, which could cause confusion

- CONTRIBUTING.rst
"parseur" est un anglicisme à éviter
> CONTRIBUTING: ajout traduction pour parse, parser

- Makefile
Running `git checkout CPYTHON_CURRENT_COMMIT` and then
`git checkout -c` can render the spinx build slower
because many sources may seem out of date.
It's better to check if we are at the correct revision and
not run *any* git operations if there's nothing to be done
> Makefile:  don't run `git checkout -` at the end of the build

- CONTRIBUTING.rst
Un ajout dans CONTRIBUTING.rst que je trouve utile.
Peut-être qu'il faut rajouter une section pour expliquer comment appliquer toutes les suggestions en un seul commit
(l'astuce c'est de passer par la vue "Changed files" et de cliquer sur "Add suggestion to batch")
> Ajout d'une section sur la gestion des suggestions

- CONTRIBUTING.rst
Suite à la proposition faite sur https://discuss.afpy.org/t/migration-des-outils-de-traductions-vers-afpy-sur-github/73/10
> Mise à jour des liens vers les dépôts des outils

- .github/workflows/tests.yml
- Makefile
CPython ajoute déjà -W dans son Makefile. Depuis le commit
f98c1623ec90508937afc1b58556e38214d70892 ("Doc: -W flag for sphinx-build
can be disabled" par Julien Palard), c'est même configurable à l'aide de
la variable SPHINXERRORHANDLING. Avec le présent commit, cette variable
fonctionne aussi dans notre traduction, ce qui permet des recompilations
plus rapides pendant la traduction avec « make SPHINXERRORHANDLING= » ou
bien « make SPHINXERRORHANDLING="-W --keep-going" ». Ce serait bien
d'avoir --keep-going par défaut, mais je ne l'ajoute pas ici car il
serait sûrement encore mieux de le mettre dans CPython directement.
> Pas de -W explicite pour Sphinx

- Makefile
make progress était incohérent avec make todo car il manquait
l'exclusion des fichiers qui ne sont pas à traduire.  Comme potodo fait
maintenant le même boulot et plus (la progression est affichée depuis la
version 0.18.0), make progress est devenu inutile.
Closes #1685
> Suppression de make progress

- tutorial/errors.po
Beaucoup de fuzzies dans ce fichier viennent du fait qu'ils ont mis en italique beaucoup de "clause machin" (try, except, else, finally).
Mais en français on les avait déjà mis en police à pas fixe, donc je n'y ai pas touché, sauf à un endroit ou c'était en italique, alors j'ai mis en police a pas fix pour garder la cohérence.
> Fuzzies in tutorial/errors.po

- tutorial/whatnow.po
Ils ont juste mis Web en minuscule upstream.
> Fuzzies in tutorial/whatnow.po

- README.rst
Add missing "g" in "discuss.afpy.org" link in the README
> Fix link to the AFPY website's forums

- reference/compound_stmts.po
> traduction de reference/compound_stmts.po

- CONTRIBUTING.rst
- Makefile
Nécessite un venv avec Python >= commit f1e29cea8516d04c16d94bcb7bf24d4e2d32ffce
voir https://github.com/python/cpython/pull/31145
> Possibilité de spécifier le port sur lequel servir la doc produite

- library/functions.po
Correction d'une typo dans `functions.po`
> Traduction de library/functions.po

- Makefile
Il n'est pas très utile de traduire ces fichiers, puisqu'ils seront
supprimés (avec les modules correspondants) en 2.12.
> Ajout des modules rendus obsolètes par la PEP 594 à EXCLUDED

- c-api/bytes.po
- c-api/exceptions.po
- c-api/init.po
- c-api/structures.po
- c-api/typeobj.po
- c-api/unicode.po
- install/index.po
- library/asyncio-api-index.po
- library/asyncio-llapi-index.po
- library/datetime.po
- library/importlib.po
- library/io.po
- library/mailbox.po
- library/optparse.po
- library/profile.po
- library/select.po
- library/smtplib.po
- library/ssl.po
- library/statistics.po
- library/stdtypes.po
- library/tkinter.dnd.po
- library/types.po
- whatsnew/2.7.po
- whatsnew/3.7.po
Based on comment: https://github.com/python/python-docs-fr/pull/1576#discussion_r875702152
```python
import re
from pathlib import Path
for path in Path.cwd().rglob("*.po"):
lines = path.read_text(encoding="utf-8").splitlines()
modified = False
for index, line in enumerate(lines):
m = re.match(r'msgid "(:[a-z-]+:`[^`<]*?`)"', line)
if m is not None:
if lines[index + 1].startswith('msgstr ""'):
lines[index + 1] = f'msgstr "{m[1]}"'
modified = True
if modified:
path.write_text("\n".join(lines) + "\n", encoding="utf-8")
```
> auto fill reStructuredText-only strings

- merge.py
The previous method could lead to problems if a dependency installed
within venv/ shipped with its own PO files.
> merge.py: Use git ls-files to get list of downstream PO files

- glossary.po
Pour des raisons que je n'ai pas creusées, la syntaxe `` :pep:`quelque
chose <numéro>` `` est une extension de Sphinx, qui n'est pas présente
dans Docutils. Cela gêne pospell, qui dit « (ERROR/3) PEP number must
be a number from 0 to 9999; "585 <585>" is invalid. »
> Reformulation dans glossary.po

- Makefile
Keep It Simple, de toute façons la CI de github passera le awk pour vérifier la longueur des lignes.
> Drop powrap from make verifs. Closes #1841.

- CONTRIBUTING.rst
- Makefile
En lien avec #1918 .
Je ne suis pas 100% convaincue que c'est la façon de faire ce changement... Suggestions (et explications) bienvenues.
Avec `make htmlview`, je réussi à générer la doc localement mais je ne vois pas comment accéder à la version traduite... j'ai regardé sur d'autres repos de doc python - [exemple](https://github.com/python/python-docs-es/blob/dfe5e62a1f23d8bc549c601b3903817a46a448bc/Makefile#L82) - et je ne vois pas trop ce que je dois changer.
C'est probablement pas le moment de faire ce changement - je vous laisse en juger :)
> màj: utilisation de htmlserve au lieu de serve dans le Makefile
