installing/index.po

Bonjour,
J'ai complété les entrées du fichier `installing/index.po`.
Je ne suis pas tout à fait sûr de mes traductions pour « Python Packaging User Guide » (« Guide Utilisateur de l'Empaquetage Python »), que je trouve assez moche même si syntaxiquement correct.
Je me demande d'ailleurs si une information n'est pas à ajouter pour les liens vers ce PyPUG, puisque pointant vers des pages en anglais.
Bonne soirée.

Complete installing section

---

library/re.po
library/string.po

Bonsoir,
J'ai ajouté les quelques traductions manquantes à `library/string.po`.
J'ai aussi commencé à compléter `library/re.po`, passant de % à 43%, mais il va encore me falloir un peu de temps pour terminer.
J'ai à ce propos du mal à traduire *match* selon les contextes : j'essaie d'utiliser *correspondre*, *valider* ou *rechercher*, mais ça rend parfois bizarre.

Complete library/string & add many translations to library/po

---

library/re.po

Bon, je continue d'avancer sur `library/re.po`, il me reste encore 110 chaîne à traduire.
Ça devrait pouvoir être bon d'ici la fin de la semaine.

Working on library/re.po

---

TRANSLATORS

Add myself to translators

---

library/re.po

Et voilà pour les 110 dernières !

Complete library/re.po

---

TRANSLATORS
library/os.po

Bonsoir,
J'ai ajouté les lignes manquantes à `library/os.po`.
J'en profite aussi pour m'ajouter au fichier `TRANSLATORS`.

Complete library/os.po

---

library/datetime.po

Bonsoir,
J'ai commencé à compléter `library/datetime.po`.
Je reprendrai dès que possible.

Working on library/datetime.po

---

library/datetime.po

Bonsoir,
J'ai continué à travailler sur `library/datetime.po`, maintenant traduit à 60%.

Working on library/datetime.po (bis)

---

library/csv.po

Bonjour,
Je viens de terminer les traductions du fichier `library/csv.po`.

Complete library/csv.po

---

library/cmd.po

I translated library/cmd.po. Please review it.

Translated library/cmd.po

---

library/subprocess.po

Bonsoir,
Chose promise, chose due, voici la traduction complète du module `subprocess` !

Complete library/subprocess.po

---

library/keyword.po

Bonsoir,
Je me suis attaqué à quelques petits modules pour changer un peu, ici le module `keyword`.

Complete library/keyword.po

---

library/html.po

Quelques difficultés *along the way* donc j'ai pris quelques libertés à certains endroits afin de rester le plus compréhensible possible. 
Je vous laisse me dire ce que vous en pensez...

Traduction du module 'html'

---

library/fractions.po

Bonsoir,
Je ne sais pas si cette PR est intégrable en l'état, parce que j'ai remarqué des erreurs dans la doc EN, que je n'ai pas encore pris la peine de reporter/corriger, je le ferai prochainement.
Mais je mets tout de même le commit en PR en attendant, avec deux traductions approximatives, pour que ça puisse être relu en attendant.

Complete library/fractions.po

---

using/cmdline.po

_hook_ traduit par "fonction automatique".
_buffer_ (de flux standard) traduit par "mémoire tampon"

"Using CommandLine" Review and Translation.

---

README.rst

Added some actions before committing changes.
Related to #261

Improves README

---

howto/regex.po

Principalement pour corriger #271

Relecture de Howto / Regex.po - début

---

library/datetime.po

Correction de coquilles

---

library/datetime.po

Quelques corrections mineures.

Minor corrections to datetime.po

---

README.rst

Explain a little bit more how to the translations deal
with python releases and how to add translation changes
related to the python life cycle.

Give more info about release life cycle and translations

---

TRANSLATORS

adding myself to translators

---

using/unix.po

je trouve cette formulation plus fidèle et naturelle

petite reformulation dans using/unix.po

---

library/errno.po

library/errno.po - corrections oubliées avant le précédent commit

---

glossary.po

Fixed fuzzys in glossary.po

---

library/collections.po

Fixed fuzzys in library/collections.po

---

library/datetime.po

Fixed fuzzys in library/datetime.po

---

library/functions.po

Fixed fuzzys in library/functions.po

---

distutils/introduction.po
faq/installed.po
howto/cporting.po

Pardon in advance, my french is a bit rusty 😧😞

Concepts et Terminologie & Compilation conditionelle

---

library/unittest.po
reference/datamodel.po

Fixed fuzzys in library/unittest.po

---

c-api/objbuffer.po

Fixed fuzzys in c-api/objbuffer.po

---

library/email.parser.po

Reprise de la PR #567 
J'ai intégré toutes les remarques de la PR.
Je préfère les ` : ::` à l'espace insécable

reprise de la PR de DeltaAlphaIotaLamdaAlphaNu sur email.parser.po

---

howto/logging.po

Fixed somme errors in howto/logging + fuzzied some unsure translations

---

howto/unicode.po

je me rends compte qu'une suggestion de ChristopheNan a pas été intégrée

Howto Unicode: rajoute une suggestion oubliée

---

license.po

Fix fuzzies in license.po

---

tutorial/introduction.po

Fix fuzzies in tutorial/introduction.po

---

reference/lexical_analysis.po

Fix fuzzies in reference/lexical_analysis.po

---

README.rst

https://github.com/Seluj78/Potodo/blob/d7ea26efec8e116b2f7d7bcb0b0bbdd126267df4/setup.py#L31

python3.6 suffit pour potodo

---

library/pathlib.po

Fix fuzzies in library/pathlib.po

---

library/filecmp.po

Fix fuzzies in library/filecmp.po

---

reference/expressions.po

Fix fuzzies in reference/expressions.po

---

library/asyncio-task.po

Fix fuzzies in library/asyncio-task.po

---

library/shutil.po

Update shutil translation

---

README.rst

perso je n'avais jamais entendu ces termes avant de me les faire suggérer par @christopheNan, et pour une fois qu'on a des beaux termes en français qui correspondent parfaitement sans être moches ou faire perdre du sens, faut pas se priver. En plus ils sont déjà dans le wiktionnaire:
https://fr.wiktionary.org/wiki/accesseur
https://fr.wiktionary.org/wiki/mutateur

"getter" et  "setter" dans le README

---

README.rst

rajoute deprecated -> obsolète dans le glossaire du README

---

README.rst

Ajout de conseils sur le futur et should dans le README

---

README.rst

ChristopheNan suggèrait ce terme à Entwanne dans la PR #961

ajout de callback->fonction de rappel dans le README

---

.travis.yml

powrap and pospell on changed files only

---

.github/ISSUE_TEMPLATE/r-servation.md

Issue template for file reservations.

---

Makefile

make powrap/pospell -> make wrap/make spell

---

README.rst

update README.rst in master branch

newly used branch is 3.8

---

.gitignore
Makefile

Or: Avoid polluting everyone's home with our venv.
Closes #657

Move venv inside of repo.

---

CONTRIBUTING.rst

Ne clos rien du tout, je n'ai pas fait d'issue.

Indication de ne pas traduire les anciens whatsnew.

---

requirements.txt

It's already 11 hours old! :wink: 
cc @Seluj78

use poutils 0.3.1

---

tutorial/stdlib.po

translating tutorial/stdlib.po

---

installing/index.po

translate installing/index.po

---

library/wsgiref.po

Correction mineure sur library/wsgiref

---

CONTRIBUTING.rst
README.rst

Quelques corrections de style et d'ortographe + j'ai accolé le glossaire à la section _conseils_ (en rajoutant deux entrées : _specify_ et _support_).
Pas d'issue associée.

Quelques modifications du README et du CONTRIBUTING.

---

library/gettext.po

Translated library/gettext.po

---

library/multiprocessing.po

Fuzzys de library/multiprocessing

---

howto/instrumentation.po
library/pdb.po

End translation for pdb.po (2)

---

faq/programming.po

Fixes #1159 
Contrôle des chaînes marqué fuzzy.
Passage de padpo et correction de petites erreurs.

Révision des fuzzy sur faq/programmaming.po

---

library/pty.po
tutorial/classes.po

Fuzzy in tutorial/classes.po

---

library/stdtypes.po

that support traduit en pendant en charge
Une traduction correcte et qui semble être les termes utilisées pour l'expression that support dans la documentation française : qui supporte

memory view correction

---

tutorial/datastructures.po

correction: < pas <=

---

CONTRIBUTING.rst

Le résultat est [ici](https://github.com/awecx/python-docs-fr/blob/contributing_misc2/CONTRIBUTING.rst).

Améliorations diverses de CONTRIBUTING.rst.

---

CONTRIBUTING.rst

Résultat [ici](https://github.com/awecx/python-docs-fr/blob/contributing_misc3/CONTRIBUTING.rst#les-%C3%A9num%C3%A9rations).

Ajout d'une entrée sur les énumérations dans le CONTRIBUTING.

---

library/audit_events.po

Translate library/audit_events.po

---

library/stdtypes.po

J'ai pas encore fait ma thèse sur les tirets comme Antoine mais je pense que je ne me trompe pas.

change triple tirets en tiret cadratin long

---

library/frameworks.po

je suis tombé dessus par hasard

frameworks -> cadriciels dans library/frameworks.po

---

CONTRIBUTING.rst
README.rst

Prévisualisable [ici](https://github.com/awecx/python-docs-fr/blob/readme2/CONTRIBUTING.rst).
Meilleure explication de la section « Traduction » + réorganisation de « Conventions ».

Améliorations du README.

---

TRANSLATORS
dict
library/datetime.po

Close #1308 
Les dernières traductions manquantes de library/datime.po.
Je m'occuperais des fuzzies après, mais j'ai moins de temps en ce moment.
Je me suis rajouté aussi dans le fichier TRANSLATORS.

Traductions manquantes library/datetime.po

---

howto/sockets.po
library/subprocess.po

C'est moi qui suit à l'origine du changement upstream. 3 fuzzies retirées mais une seule modif car 2 trads faisaient la correction downstream.

fuzzies Posix -> POSIX

---

whatsnew/3.9.po

reprise de #1366 .
Vu que c'est de la trad qui est utile maintenant et qui sera plus lue dans ~1 an, pas besoin que ça soit absolument parfait.

whatsnew 3.9

---

CONTRIBUTING.rst

Add missing `code-block`
Homogenize the number of new lines after code blocks to 2 lines.

Add missing `code-block`

---

CONTRIBUTING.rst

Reverts python/python-docs-fr#1364

Revert "Add missing `code-block`"

---

library/tarfile.po

Translation of tarfile.po from english to french (#1274)

---

CONTRIBUTING.rst

Basée sur #1372 .
J'ai volontairement pas fait le dernier paragraph, trop spécial, trop technique, ceux qui en ont besoin ont pas besoin d'option longues

CONTRIBUTING.rst: options longues dans les blocs de code

---

copyright.po
dict
glossary.po
license.po
sphinx.po

MàJ vers Python 3.9 + quelques fuzzys.

MàJ des fichiers à la racine.

---

library/colorsys.po

Mise à jour de la traduction de library/colorsys.po

---

dict
library/asyncio-task.po

(cherry picked from commit 37cc13ea350b100982362a899d674bf42eed5606)

Traduction pour library/asyncio-task.po (#1403)

---

whatsnew/3.9.po

FIX: Those were missed by pospell < 1.0.6.

---

glossary.po

Traduction de glossary.po

---

license.po

Traduction de license.po

---

README.rst

Et une motivation à devenir membre de l'AFPy, ou carrément faire un don à l'AFPy.
En fait je pense qu'on devrait mettre l'AFPy plus en avant dans ce projet, qui est un projet de l'AFPy à la base (github.com/afpy/python_doc_fr). Si vous avez une idée de petite phrase AFPyenne à rajouter, je prend.

Lien vers le discourse.

---

.github/pr-title-checker-config.json
.github/workflows/pr-title-cheker.yml

Added title checker

---

.github/workflows/pr-title-cheker.yml
.github/workflows/tests.yml

Update tests.yml for all french names

---

library/time.po

Relecture de library/time.po

---

CONTRIBUTING.rst

Modifications mineures sur le guide de contribution.
Prévisualisation [ici](https://github.com/awecx/python-docs-fr/blob/readme/CONTRIBUTING.rst)

Modifications mineures du guide de contribution.

---

library/csv.po

Correction fuzzy

---

README.rst

Je viens de refaire la vidéo gource :)

Mise à jour de la vidéo gource

---

README.rst

Prévisualisation [ici](https://github.com/awecx/python-docs-fr/tree/readme2)

(Encore) quelques modifications du README.

---

library/timeit.po

Closes #1558
Révision d'un fuzzy de library/timeit.po

Traduction de library/timeit.po

---

library/calendar.po

Closes  #1562
Révision d'une fuzzy (je n'ai rien fait...)

Traduction de library/calendar.po

---

library/datetime.po

Révision de fuzzies de library/datetime.po, plus 4 traductions manquantes

Traduction de library/datetime.po

---

library/collections.abc.po

Closes #1564
Révisions des fuzzies

Traduction de library/collections.abc.po

---

library/ipaddress.po

Traduction de la fuzzy de ipaddress.po

---

library/typing.po

Corrections à la traduction de library/typing.po

---

library/contextlib.po

Fuzzy de library/contextlib.po

---

library/asyncio.po

Fuzzy de library/asyncio.po.

---

CONTRIBUTING.rst
README.rst

This is shorter and avoid problem with links due to double hash

Use the libera webchat

---

library/gc.po

Traduction de library/gc.po

---

dict
library/pickle.po

(Avec deux-trois chaînes que je ne savais pas comment traduire, où les suggestions seront bienvenues.)
Closes #1620.

Traduction de library/pickle.po

---

CONTRIBUTING.rst

Mentionne le paquet Poutils qui permet d'installer tous les outils à la
fois, et ajoute une note sur l'installation du bon dictionnaire Hunspell
sous Debian.
Closes #1681.

Amélioration de CONTRIBUTING.rst sur Poutils

---

tutorial/index.po

Juste le "Web" passé en minuscule"

Fuzzies in tutorial/index.po

---

tutorial/interpreter.po

(je fais une PR par fichier pour qu'ils soit marqués comme reservés dans potodo)

Fuzzies in tutorial/interpreter.po

---

CONTRIBUTING-CORE.rst
Makefile

Alternative to https://github.com/python/python-docs-fr/pull/1630

Use our own cpython clone.

---

extending/newtypes_tutorial.po

Je pense que je vais m'arrêter là pour le moment sur ce fichier, si j'attaque le reste ce sera pour une autre péèrre.

Work on extending/newtypes_tutorial.po

---

CONTRIBUTING.rst
Makefile

Reprise de #1764 cc @Fipaddict @Jean-Abou-Samra

Make wrap to actually wrap, not just check.

---

library/zipimport.po

Traduction de library/zipimport.po

---

CONTRIBUTING.rst

Traduction de 'to sort'

---

using/mac.po

Fuzzys et corrections mineures

---

copyright.po

Mise à jour de copyright.po

---

whatsnew/3.10.po

c'est pas du grand art, mais c'est pas une grande page non plus

whatsnew/3.10.po: fuzzies
